### PR TITLE
fix: do not include self when using findAll

### PR DESCRIPTION
**Pull request by lmiller1990**
resolves https://github.com/vuejs/test-utils/issues/1233

Seems too easy 🤔

### CODE REVIEW

**Comment by lmiller1990** [comment]
cc @freakzlike @aethr WDYT?

**Comment by xanf** [comment]
:eyes: Looking on this right now

**Comment by lmiller1990** [comment]
@xanf pushed a commit to fix that.

**Comment by xanf** [comment]
@lmiller1990 looking

**Comment by xanf** [comment]
@lmiller1990 while reviewing your PR I've found another failing case - https://github.com/vuejs/test-utils/pull/1392/files#diff-9835123bc80f420fd7ebbcc25a72c73e7f2c8934bac14a9a3bbe6e1dca3569f7R356

And I believe I've figured more elegant approach in #1392 
Could you please look at that (basically we simply separated implementations of `findAll` for VueWrapper and DOMWrapper.
Feel free to close that PR is favor of this one if you feel that this approach is better

/cc @cexbrayat

**Pull request closed without merging**
