### PR TITLE
feat: add `promisify` utility function

### PR DESCRIPTION
**Pull request by gustavosbarreto**
## Description

This PR introduces a new utility function called `promisify`. The function is especially useful for testing asynchronous methods in components.

## Context and Motivation
    
Asynchronous operations are common in component methods, and dealing with asynchronous behavior can be challenging. The `promisify` function aims to simplify the handling of asynchronous methods by automatically wrapping them in an array of promises. This ensures that each promise is settled before making assertions, providing a convenient way to handle asynchronous behavior in tests.

## Usage
   
To use the `promisify` function, simply pass a Vue component object as an argument. The function will iterate over the component's methods and wrap the asynchronous ones in promises. All promises will be returned, and you need to fulfill them by calling `Promise.all` before making assertions.

### Example

Here is an example that demonstrate the usage of the `promisify` function:
    
```ts
it("sets clicked to true after simulating delay", async () => {
  const Component = defineComponent({
    template: '<button @click="clickHandler()"/>',
    data: () => ({
      clicked: false,
    }),
    methods: {
      async clickHandler() {
        await simulateDelay({ delayInMs: 100 })
        this.clicked = true
      },
    },
  })

  const wrapper = mount(Component)
  const promises = promisify(wrapper) 👈

  await wrapper.find("button").trigger("click")

  await Promise.all(promises) 👈

  expect(wrapper.vm.clicked).toBe(true)
});
```

## Testing

Unit tests have been added in the `promisify.spec.ts` file to ensure the correctness of the promisify function. The tests cover various scenarios, including synchronous methods, asynchronous methods, asynchronous methods with parameters, asynchronous methods that return values, and multiple asynchronous methods.

> Please note that this is my first contribution to Vue, and there may be potential errors or areas for improvement in my implementation. I am open to any suggestions, feedback, or guidance from the community to enhance the functionality or ensure that the pull request aligns with the project's guidelines and requirements.

### CODE REVIEW

**Comment by freakzlike** [comment]
Hey @gustavosbarreto, thanks for your PR. It's well described but I actually don't get the point why this is needed and cannot be done with `await flushPromises()`?

Furthermore I think it's not working with `setup` function?

**Comment by freakzlike** [comment]
I've taken a look at your async implementation and saw that you are using `setTimeout` without mocking the timer. This might be the issue why you are not able to use `await flushPromises()`.

I've created a reproduction and updated your tests to use [`vi.runOnlyPendingTimers()`](https://vitest.dev/api/vi.html#vi-runonlypendingtimers) and `await flushPromises()` instead of `promisify`.

https://stackblitz.com/edit/github-a4d3hr?file=src%2F__tests__%2FApp.spec.ts

```typescript
vi.useFakeTimers();

it('creates a promise for asynchronous method', async () => {
  // ...

  vi.runOnlyPendingTimers();
  await flushPromises();

  // ...
});
```

Furthermore your tests are actually waiting for the timeout which increases your unit test time for each one by 100ms instead of running immediately

**Comment by cexbrayat** [comment]
@gustavosbarreto Thanks for your contribution, but I agree with @freakzlike : the proper way to test this kind of code is to rely on vitest for running the timers, or using fake timers.
We really appreciate contributions though, so next time don't hesitate to ask a question in the GitHub discussion or in an existing issue if you feel like writing some code for VTU

**Comment by gustavosbarreto** [comment]
@cexbrayat @freakzlike Thanks for your feedback. I understand the importance of proper testing, and I apologize for any confusion caused. I want to clarify that I'm not specifically testing timers in this implementation. The usage of `simulateDelay` with timers was simply used to demonstrate a long-duration operation, which could be replaced with any other asynchronous action.

**Pull request closed without merging**
