### PR TITLE
fix: check if component unmounted in Wrapper.exists()

### PR DESCRIPTION
**Pull request by Djaler**

### CODE REVIEW

**Review by cexbrayat — APPROVED** [review]
LGTM, thanks fot the PR 👍

**Comment by xanf** [comment]
@Djaler thank you for catching this issue!

I've addead a bit alternate approach (just removing conditional and adding logic in child class)

@cexbrayat thank you for merging!

**Comment by Djaler** [comment]
Thx for the quick approve. Any chance to release it soon, so I can use the fix in my project? 😅

**Comment by cexbrayat** [comment]
@Djaler we need to fix another issue first, so the release is blocked by #1601 for now
Once that gets sorted out and merged, we'll cut a new release. It might take some time though

**Pull request merged**
